version: '2'
services:
  postfix:
    image: juanluisbaptiste/postfix:latest
    ports:
    - "25:25"
    env_file:
      - .env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
